apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-pv
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stateful-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: headless-stateful-svc
  labels:
    app: headless-stateful
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: stateful
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulapp
spec:
  serviceName: headless-stateful-svc
  replicas: 3
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      labels:
        app: stateful
    spec:
      containers:
        - name: stateful-container
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/visalrepository:${{ steps.docker_build.outputs.commit_id }}
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            runAsUser: 0
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: stateful-pvc
